import type { ComponentType } from 'react'
import {
  SiAmazonwebservices,
  SiGooglecloud,
  SiKubernetes,
  SiAmazoneks,
  SiDocker,
  SiHelm,
  SiIstio,
  SiTerraform,
  SiAnsible,
  SiGnubash,
  SiPython,
  SiArgo,
  SiJenkins,
  SiGithubactions,
  SiGitlab,
  SiGrafana,
  SiPrometheus,
  SiAmazoncloudwatch,
  SiElastic,
  SiKibana,
  SiOpentelemetry,
  SiPagerduty,
  SiSlack,
  SiAmazonrds,
  SiAmazondocumentdb,
  SiOpensearch,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiApachekafka,
  SiAkamai,
  SiNginx,
  SiLinux,
  SiGit,
  SiGithub,
  SiAmazons3,
} from 'react-icons/si'
import {
  Workflow,
  ScrollText,
  BookOpenCheck,
  FileSearch,
  Network,
  Waypoints,
  ShieldCheck,
  Cloud,
} from 'lucide-react'

export type IconDef = { Icon: ComponentType<{ size?: number; className?: string }>; color: string }

/** Brand marks in their own colours; generic concepts fall back to a lucide glyph. */
export const ICONS: Record<string, IconDef> = {
  aws: { Icon: SiAmazonwebservices, color: '#FF9900' },
  gcp: { Icon: SiGooglecloud, color: '#4285F4' },
  k8s: { Icon: SiKubernetes, color: '#326CE5' },
  eks: { Icon: SiAmazoneks, color: '#FF9900' },
  docker: { Icon: SiDocker, color: '#2496ED' },
  helm: { Icon: SiHelm, color: '#6C8CF5' },
  istio: { Icon: SiIstio, color: '#7B61FF' },
  terraform: { Icon: SiTerraform, color: '#A06CEA' },
  ansible: { Icon: SiAnsible, color: '#EE0000' },
  bash: { Icon: SiGnubash, color: '#8CD94E' },
  python: { Icon: SiPython, color: '#4B8BBE' },
  devtron: { Icon: Workflow, color: '#7c8aff' },
  argo: { Icon: SiArgo, color: '#EF7B4D' },
  jenkins: { Icon: SiJenkins, color: '#E8543F' },
  ghactions: { Icon: SiGithubactions, color: '#2088FF' },
  gitlab: { Icon: SiGitlab, color: '#FC6D26' },
  grafana: { Icon: SiGrafana, color: '#F46800' },
  prometheus: { Icon: SiPrometheus, color: '#E6522C' },
  cloudwatch: { Icon: SiAmazoncloudwatch, color: '#FF4F8B' },
  alertmanager: { Icon: SiPrometheus, color: '#E6522C' },
  elastic: { Icon: SiElastic, color: '#43A047' },
  kibana: { Icon: SiKibana, color: '#E8488B' },
  otel: { Icon: SiOpentelemetry, color: '#F5A800' },
  signoz: { Icon: ScrollText, color: '#E75536' },
  pagerduty: { Icon: SiPagerduty, color: '#06AC38' },
  slack: { Icon: SiSlack, color: '#E01E5A' },
  runbook: { Icon: BookOpenCheck, color: '#39c5cf' },
  postmortem: { Icon: FileSearch, color: '#bc8cff' },
  rds: { Icon: SiAmazonrds, color: '#527FFF' },
  documentdb: { Icon: SiAmazondocumentdb, color: '#527FFF' },
  opensearch: { Icon: SiOpensearch, color: '#4B9CD3' },
  postgres: { Icon: SiPostgresql, color: '#4E93C4' },
  mysql: { Icon: SiMysql, color: '#3E8DA8' },
  redis: { Icon: SiRedis, color: '#FF4438' },
  kafka: { Icon: SiApachekafka, color: '#9AA5B1' },
  akamai: { Icon: SiAkamai, color: '#1EA5E0' },
  cloudfront: { Icon: Cloud, color: '#B07BFF' },
  nginx: { Icon: SiNginx, color: '#12A85D' },
  lb: { Icon: Waypoints, color: '#FF9900' },
  vpc: { Icon: Network, color: '#58a6ff' },
  linux: { Icon: SiLinux, color: '#FCC624' },
  git: { Icon: SiGit, color: '#F05033' },
  github: { Icon: SiGithub, color: '#f5f1ec' },
  s3: { Icon: SiAmazons3, color: '#7FB93F' },
  iam: { Icon: ShieldCheck, color: '#E8586B' },
}
